name: Build ESPHome Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Untuk trigger manual

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build ESPHome firmware
      uses: esphome/compile-script@v1
      with:
        platform: esp32
        device: device.yaml
        
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v3
      with:
        name: esp32-firmware
        path: build/*.bin
